include $(GOROOT)/src/Make.inc

STATS=
#STATS=stats_http.go

TARG=code.google.com/p/go9p/p/srv
GOFILES=\
	conn.go\
	fcall.go\
	file.go\
	respond.go\
	srv.go\
	$(STATS)\

include $(GOROOT)/src/Make.pkg
