include $(GOROOT)/src/Make.$(GOARCH)

#STATS=none
STATS=http

TARG=go9p.googlecode.com/hg/p/srv
GOFILES=\
	conn.go\
	fcall.go\
	file.go\
	respond.go\
	srv.go\
	stats_$(STATS).go\

include $(GOROOT)/src/Make.pkg
