include $(GOROOT)/src/Make.inc

STATS=
#STATS=stats_http.go
TARG=code.google.com/p/go9p/p/clnt
GOFILES=\
	clnt.go\
	close.go\
	mount.go\
	open.go\
	pool.go\
	read.go\
	remove.go\
	stat.go\
	walk.go\
	write.go\
	$(STATS)\
	tag.go\

include $(GOROOT)/src/Make.pkg
