include $(GOROOT)/src/Make.$(GOARCH)

TARG=code.google.com/p/go9p/p/clnt
GOFILES=\
	clnt.go\
	close.go\
	mount.go\
	open.go\
	pool.go\
	read.go\
	remove.go\
	stat.go\
	walk.go\
	write.go\

include $(GOROOT)/src/Make.pkg
